.circleci/config.yml, .eslintrc, .gitignore, .npmrc, .taprc, CHANGELOG.md, LICENSE, README.md, docs/migrating-from-other-versions.md, index.js, lib/backoff-with-jitter.js, lib/constants.js, lib/lang/type-of.js, lib/logger.js, lib/validators/check-string-param.js, lib/validators/has.js, lib/validators/index.js, lib/validators/is-valid-timestamp.js, package.json, test/common/create-options.js, test/common/index.js, test/index.js, test/loadtest.js, test/logger-errors.js, test/logger-instantiation.js, test/logger-log.js, test/unit/lang/type-of.js, types.d.ts
This is a refactor of the last version from logdna/nodejs.  This version
uses a different npm namespace and repository, and fixes some usage
difficulties.
In general, callbacks do not work with a "flushing"
app due to the asynchronous nature of HTTP requests and dealing with
errors and retries.  Using an EventEmitter is much more appropriate,
so callbacks have been removed in this version as compared to
logdna/nodejs@3.5.1
CHANGE LIST:
* Removed `debug` since it's not compatible everywhere.  See
issue (https://github.com/logdna/nodejs/issues/89)
* `class Logger` forces the use of the `new` keyword
* Helper functions are broken out to declutter the class file
* `configs.js` was renamed to the more appropriate `constants.js`
* Made all variables consistent in naming convention …
=> improvement: refactor from logdna/nodejs

CHANGELOG.md
Contains code improvements carried over from the soon-to-be-deprecated
`nodejs` package.
Semver: major
=> bump: Release @logdna/logger v1.0.0

CHANGELOG.md, docs/migrating-from-other-versions.md
The file link was missing the `.md` extension.
Semver: patch
=> fix(docs): Fix broken Best Practices link in the migration document

README.md, lib/constants.js, lib/logger.js, lib/payloads.js, test/common/create-options.js, test/logger-agent-log.js, test/logger-errors.js, test/logger-instantiation.js
The node client should be able to serve as the transport mechanism
to the ingestion service for anything using nodejs.  LogDNA's agent
can be streamlined by re-using this package (and its retry logic)
to send data to the cloud.  This commit adds a method that should
only be used by the LogDNA agent, but supports the data structure
necessary for ingestion.
Semver: minor
Ref: LOG-7103
=> feat(agentLog): Add a logging method that can be called by the agent

README.md, lib/logger.js, test/logger-agent-log.js, test/logger-errors.js, test/logger-log.js
**improvement: Handle partial-success 207 responses**
If we get a partial-success (207) response, emit errors for
the failed lines.  This maintains feature parity with the agent
in preparation for using this client inside of the agent.
Semver: minor
Ref: LOG-7151
---
**improvement: Add more error codes for retry**
This change enhances our list of error codes for status as well as
connection-based error codes.  This will allow the client to be more
intelligent about when to retry.
Semver: minor
Ref: LOG-7151
=> improvement: Add more error retry codes, and handle 207 partial-success responses

types.d.ts
Type definitions were using old module name (logdna)
Changes the module name to @logdna/logger
=> Fix module name in types

README.md, lib/constants.js, lib/logger.js, package.json, test/common/create-options.js, test/logger-instantiation.js, test/logger-log.js
Certain implementations may require traffic to pass through a proxy
before reaching the outside world (and the LogDNA server).  This
uses the `https-proxy-agent` package to add proxy capability
to the HTTP agent.
Semver: minor
Ref: LOG-7175
=> feat: Add proxy support

package.json
We should do our best to enforce our desired conventional
commit style, especially since PRs may come from the
public.  This sets up basic rules for validating the
conventional commit style.
Semver: minor
Ref: LOG-7183
=> package: Add pre-commit hooks to enforce commit message style

types.d.ts
Logger now extends from EventEmitter
(sidenote: apologies for not following the commit guidelines before, I wasn't thinking)
=> fix: fix out-of-sync logger type definition

CHANGELOG.md, package.json
This has another Typescript definition fix, and
increases the default timeout to 30 seconds.
Semver: patch
=> package: bump to @logdna/logger@1.3.1

package.json
eslint does not need to be a peerDependency.  It will work fine
as a dev dependency.
Ref: LOG-7287
Fixes: https://github.com/logdna/logger-node/issues/18
Semver: patch
=> fix: Remove eslint as a peerDependency

CHANGELOG.md, package.json
This removes `eslint` as a peer dependency.
Semver: patch
=> package: bump to @logdna/logger@1.3.2

README.md, lib/logger.js, test/common/create-options.js, test/loadtest.js, test/logger-errors.js, test/logger-instantiation.js
BREAKING CHANGE: The 'error' event's message was changed
Retry-able errors can get noisy considering they're
typically related to intermittent client/server errors
(currently being addressed), and there is no loss of data.
Rather than swallowing these errors, the user should be able
to control how noisy the errors are.  The default will be to
NOT emit retry-able errors.
To reduce confusion between irrecoverable errors, the `Error`
message was changed to reflect whether or not it's a temporary (or
retry-able) error.  Although minor, this is considered a breaking
change.
Semver: major
Ref: LOG-7639
Fixes: https://github.com/logdna/logger-node/issues/24
=> feat: `ignoreRetryableErrors` will not emit retry-able errors

README.md, lib/logger.js, test/common/create-options.js, test/logger-instantiation.js, test/logger-log.js
When the logger is bundled for browser use, attempting to set the
user-agent can throw a console error of 'Refused to set unsafe header
"user-agent".'  Although the request is still sent, this makes for very
chattery console errors which is undesirable. Since not ALL browsers print
this error, the solution needs to be flexible enough to try and set the
user-agent for most cases, but also allow for it to be turned off. The
`sendUserAgent` constructor option, if set to `false` will omit the
user-agent header.  It is `true` by default.
Semver: minor
Ref: LOG-7793
Fixes: https://github.com/logdna/logger-node/issues/27
=> fix: Omit user-agent header if `sendUserAgent` option is `false`

index.js, lib/logger.js, package.json, test/index.js, test/loadtest.js, test/logger-agent-log.js, test/logger-errors.js, test/logger-instantiation.js, test/logger-log.js, test/unit/lang/type-of.js
**feat: Add more context (headers) to the errors**
In some cases, HTTP errors can happen with things
like invalid header values. In order to properly debug
such situations, we need to report as much context
about the connection that we safely can. Part of this
will be exposing the header values. The URL of the
connection has also been requested in the past, and so
that has also been added to the error's metadata.
Semver: minor
Fixes: https://github.com/logdna/logger-node/issues/34
---
**deps: eslint-config-logdna@4.0.2**
Bump the eslint (and sensible) dependencies.
Semver: patch
=> feat: Add more context (headers) to the errors

lib/constants.js, lib/logger.js, test/logger-instantiation.js
Part of the user-agent header value can be passed in
during instantiation. This value should be stripped
of all characters that would be considered invalid and
thus cause an HTTP header error. Such characters are
newlines and the like, so for our purposes, we will
strip all non-printable characters from the user-agent
value.
Semver: patch
Fixes: https://github.com/logdna/logger-node/issues/34
=> fix: Remove invalid characters from the user-agent

lib/logger.js, test/logger-errors.js
This error code can be thrown due to a disconnected
network connection. It should certainly be a retryable
error.
Semver: minor
Fixes: https://github.com/logdna/logger-node/issues/40
=> feat: Add EADDRNOTAVAIL to the retryable error codes

lib/logger.js
Axios has a maxBodyLength which defaults to
2000 bytes. Given that the payloads for the
logger can be much larger than this, turn this
limitation off. It should be noted that there's
only 1 report of this in the wild, and the problem
has not been able to be reproduced.
Semver: patch
Fixes: https://github.com/logdna/logger-node/issues/44
=> fix: Turn off maxBodyLength in Axios

.all-contributorsrc, Jenkinsfile, README.md, package.json, tools/test-ci.sh
**fix(docs): Correct bad documentation for logging errors**
`Error` objects are largely non-enumerable, so they
don't serialize well. Improve the docuementation for
how to properly log errors.
Semver: patch
Fixes: https://github.com/logdna/logger-node/issues/48
---
**docs: add @esatterwhite as a contributor**
---
**docs: add @nhuttm as a contributor**
---
**docs: add @mdeltito as a contributor**
---
**docs: add @alanzchen as a contributor**
---
**docs: add @ligerzero459 as a contributor**
---
**chore(contributors): Use all-contributors**
This removes the hardcoded `contributors` list in
package.json and moves to the common `all-contributors`
package to list contributors in the README.
---
**docs: add @relative as a contributor**
---
**docs: add @darinspivey as a contributor**
--- …
=> fix(docs): Correct bad documentation for logging errors

package.json
The last update changed to using an npm `files` whitelist
in order to keep the package size down. The typescript
definitions file and the docs directory were left out.
Fixes: #55
=> fix(package): Include missing files and type definitions

README.md, lib/constants.js, lib/logger.js, test/common/create-options.js, test/logger-errors.js, test/logger-instantiation.js, types.d.ts
Allow users to optionally specify a maximum number of
attempts to send in case of retryable errors, instead
of retrying indefinitely.
The logger will accept an integer "maxAttempts" option,
which gives the total number of attempts (including
the first) when retryable errors are encountered.
When the limit is reached, errors that would otherwise
be considered retryable are instead treated as non-retryable.
If "maxAttempts" is negative (or not specified),
the logger will continue to retry indefinitely.
* lib/logger.js: Add definitions and initialization for
maxAttempts. Add convenience method _shouldRetry() to
determine whether or not to retry given a specific
error code.
* lib/constants.js: Add MAX_ATTEMPTS default value.
* test/common/create-options.js: Added check for default
value of …
=> feat(max-attempts): support retry limits

README.md, lib/logger.js, test/common/create-options.js, test/logger-errors.js, test/logger-instantiation.js, test/logger-log.js, types.d.ts
With this change, the user may specify a `verboseEvents`
boolean option when creating a logger.  If true, the logger
will include the buffer of messages that was sent (or attempted
to be sent) when emitting `send` and `error` events, in the
`buffer` member of the `send` event and the `meta.buffer` member
of the `error` event.  This enables users to correctly identify
the messages that were transmitted for metrics in case of success,
and to implement higher-level retry behaviors in case of errors.
* lib/logger.js: Add support for `verboseEvents` option.
(send): When emitting `send` and `error` events, include the
message buffer involved when `verboseEvents` is true.  In case
of partial success, each `error` event will include a buffer
containing only the specific line that failed; and the …
=> feat: optionally include buffer in send/error events.

package.json
This fixes an identified security vulerability in one of
axios' dependencies, `follow-redirects`.
Fixes: #63
=> chore(deps): axios@0.25.0

lib/logger.js, test/logger-instantiation.js
* lib/logger.js: Extract logic for computing size of
a payload to a separate function so it can be overridden
or expanded cleanly (for example if we choose to start
measuring the size of the entire payload object instead
of just the length of the log message).
* test/logger-instantiation.js: Update tests relating to
count and set of methods in Logger.
No other test changes since _getPayloadSize is a trivial
internal utility function at this time.
=> refactor: extract _getPayloadSize method

lib/logger.js, test/logger-instantiation.js
* lib/logger.js: Extract logic for creating a
serialized representation of the buffer to be
sent to a separate function, so we may cleanly
augment or override it in the future (for example
if we want to add a signature or checksum to the
transmitted data).
* test/logger-instantiation.js: Update tests relating
to count and set of methods in Logger; sort the list of
methods so we can predict the order without having to
run the test once when adding methods.
No explicit test for the extracted function at this
point since it's a trivial internal utility, and the
format returned is implicitly tested by existing tests.
=> refactor: extract _serializeBuffer method

lib/logger.js, test/logger-errors.js, test/logger-log.js
* lib/logger.js: use Promise.resolve().then() to call _serializeBuffer,
so it can optionally be async in subclasses.
* test/logger-log.js:
* test/logger-errors.js: Add tests for async _serializeBuffer, and
error handling thereof.
Note: this _looks like_ a large change but it's not really -- just diff getting confused by the indentation changes
The substance of the change is to go from this:
```
const data = this._serializeBuffer(buffer)
// do stuff with data
```
to this:
```
Promise.resolve(this._serializeBuffer(buffer))
.then((data) => {
// do stuff with data
})
.catch((error) => {
// Handle errors in resolution of _serializeBuffer
})
```
I did not try to refactor the code in `// do stuff with data` because it's got a bit too much dependency on shared state vis a vis local variables.  I …
=> fix(send): Allow _serializeBuffer() to be async

Jenkinsfile, README.md, package.json, test/logger-errors.js, test/logger-log.js
**fix(ci): Specify agent label and remove `beforeAgent`**
These changes are necessary to conform to changes made to our
build system which segment the agents based on app concern.
Fixes: #72
---
**chore(deps): Install @logdna/commitlint-config@2.0.0**
This package will enforce Conventional commit style to be in line
with the Company's preference. Public PRs will have to adhere to
those standards for their commit messages.
Fixes: #72
---
**chore(deps): semantic-release@19.0.3**
---
**chore(deps): eslint@8.18.0 and eslint-config-logdna@6.1.0**
=> chore(deps): Install @logdna/commitlint-config@2.0.0

Jenkinsfile, README.md
**fix(doc): Best practices code snipit does not work as an example**
The code snipit under "Best Practices" was meant to be a snipit for how
to configure an error listener, but it could be misconstrued as a
working example. This commit makes it work and disambiguates it.
Fixes: #74
---
**chore(ci): Test with node 18**
This starts testing node18 in the testing matrix.
=> fix(doc): Best practices code snipit does not work as an example

.gitignore, lib/logger.js, test/logger-errors.js, test/logger-instantiation.js
Change auth schema to be apiKey so that
it works with both log analysis and pipeline
Fixes: #86
=> fix: make compatible with pipeline
